"""create daily_summaries and weather_records

Revision ID: 1a2656b07686
Revises: 
Create Date: 2026-05-26 10:19:01.458273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2656b07686'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_key', sa.String(), nullable=False),
    sa.Column('temp_avg', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('humidity_avg', sa.Float(), nullable=True),
    sa.Column('pressure_avg', sa.Float(), nullable=True),
    sa.Column('wind_avg', sa.Float(), nullable=True),
    sa.Column('wind_max_gust', sa.Float(), nullable=True),
    sa.Column('wind_direction_avg', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('sunshine_hours', sa.Float(), nullable=True),
    sa.Column('solar_max_wm2', sa.Float(), nullable=True),
    sa.Column('uv_max', sa.Float(), nullable=True),
    sa.Column('et_mm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=True)
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_key', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_records')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
